name = "DHBW Lean Game"
version = "1.1.0"
extra_files = "extras"
intro = "src/intro.lean"
source_base_url = "https://raw.githubusercontent.com/mmasdeu/topologygame/main/"

[[worlds]]
name = "dictionary"
id = 1
levels = [
        "src/dictionary/dictionary.lean",
]

