name = "Lean Topology game"
version = "1.1.0"
extra_files = "extras"
intro = "src/intro.lean"
source_base_url = "https://raw.githubusercontent.com/mmasdeu/topologygame/main/"

[[worlds]]
name = "Set theory"
id = 1
levels = [ "src/set_theory_world/level*.lean" ]

